INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (1, 'Neck pillow', 'Conventional Neck Pillow', NULL, 'Conventional Neck Pillow #1', '/img/1.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (2, 'Neck pillow', 'Conventional Neck Pillow', NULL, 'Conventional Neck Pillow #2', '/img/2.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (3, 'Neck pillow', 'Conventional Neck Pillow', NULL, 'Conventional Neck Pillow #3', '/img/3.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (4, 'Neck pillow', 'Conventional Neck Pillow', NULL, 'Conventional Neck Pillow #4', '/img/4.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (5, 'Neck pillow', 'Conventional Neck Pillow', NULL, 'Conventional Neck Pillow #5', '/img/5.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (6, 'Neck pillow', 'Animals Neck Pillow', NULL, 'Animals Neck Pillow #1', '/img/6.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (7, 'Neck pillow', 'Animals Neck Pillow', NULL, 'Animals Neck Pillow #2', '/img/7.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (8, 'Neck pillow', 'Animals Neck Pillow', NULL, 'Animals Neck Pillow #3', '/img/8.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (9, 'Neck pillow', 'Animals Neck Pillow', NULL, 'Animals Neck Pillow #4', '/img/9.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (10, 'Neck pillow', 'Animals Neck Pillow', NULL, 'Animals Neck Pillow #5', '/img/10.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (11, 'Back cushion', 'Conventional Back Cushion', NULL, 'Conventional Cushion For Leaning On #1', '/img/11.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (12, 'Back cushion', 'Conventional Back Cushion', NULL, 'Conventional Cushion For Leaning On #2', '/img/12.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (13, 'Back cushion', 'Conventional Back Cushion', NULL, 'Conventional Cushion For Leaning On #3', '/img/13.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (14, 'Back cushion', 'Conventional Back Cushion', NULL, 'Conventional Cushion For Leaning On #4', '/img/14.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (15, 'Back cushion', 'Conventional Back Cushion', NULL, 'Conventional Cushion For Leaning On #5', '/img/15.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (16, 'Back cushion', 'Conventional Back Cushion', NULL, 'Conventional Cushion For Leaning On #6', '/img/16.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (17, 'Back cushion', 'Conventional Back Cushion', NULL, 'Conventional Cushion For Leaning On #7', '/img/17.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (18, 'Back cushion', 'Conventional Back Cushion', NULL, 'Conventional Cushion For Leaning On #8', '/img/18.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (19, 'Back cushion', 'Animal Back Cushion', NULL, 'Animal Back Cushion #1', '/img/19.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (20, 'Back cushion', 'Animal Back Cushion', NULL, 'Animal Back Cushion #2', '/img/20.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (21, 'Back cushion', 'Animal Back Cushion', NULL, 'Animal Back Cushion #3', '/img/21.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (22, 'Back cushion', 'Animal Back Cushion', NULL, 'Animal Back Cushion #4', '/img/22.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (23, 'Sofa cushion', 'Japanese Cushion', NULL, 'Japanese Cushion #1', '/img/23.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (24, 'Sofa cushion', 'Japanese Cushion', NULL, 'Japanese Cushion #2', '/img/24.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (25, 'Sofa cushion', 'Japanese Cushion', NULL, 'Japanese Cushion #3', '/img/25.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (26, 'Sofa cushion', 'Sofa', NULL, 'Sofa #1', '/img/26.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (27, 'Sofa cushion', 'Sofa', NULL, 'Sofa #2', '/img/27.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (28, 'Sofa cushion', 'Sofa', NULL, 'Sofa #3', '/img/28.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (29, 'Sofa cushion', 'Sofa', NULL, 'Sofa #4', '/img/29.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (30, 'Sofa cushion', 'Sofa', NULL, 'Sofa #5', '/img/30.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (31, 'Toy', 'Children\'s Toys', NULL, 'Children\'s Toys #1', '/img/31.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (32, 'Toy', 'Children\'s Toys', NULL, 'Children\'s Toys #2', '/img/32.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (33, 'Toy', 'Children\'s Toys', NULL, 'Children\'s Toys #3', '/img/33.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (34, 'Toy', 'Children\'s Toys', NULL, 'Children\'s Toys #4', '/img/34.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (35, 'Toy', 'Children\'s Toys', NULL, 'Children\'s Toys #5', '/img/35.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (36, 'Toy', 'Children\'s Toys', NULL, 'Children\'s Toys #6', '/img/36.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (37, 'Toy', 'Children\'s Toys', NULL, 'Children\'s Toys #7', '/img/37.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (38, 'Toy', 'Children\'s Toys', NULL, 'Children\'s Toys #8', '/img/38.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (39, 'Toy', 'Children\'s Toys', NULL, 'Children\'s Toys #9', '/img/39.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (40, 'Toy', 'Pet Toys', NULL, 'Pet Toys #1', '/img/40.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (41, 'Toy', 'Pet Toys', NULL, 'Pet Toys #2', '/img/41.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (42, 'Toy', 'Pet Toys', NULL, 'Pet Toys #3', '/img/42.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (43, 'Toy', 'Pet Toys', NULL, 'Pet Toys #4', '/img/43.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (44, 'Toy', 'Pet Toys', NULL, 'Pet Toys #5', '/img/44.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (45, 'Toy', 'Pet Toys', NULL, 'Pet Toys #6', '/img/45.jpg');
INSERT INTO `product`(`id`, `class1`, `class2`, `class3`, `name`, `picture`) VALUES (46, 'Toy', 'Pet Toys', NULL, 'Pet Toys #7', '/img/46.jpg');
